// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsBiometricSignatureApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsBiometricSignatureApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsBiometricSignatureApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashBiometricSignatureApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashBiometricSignatureApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashBiometricSignatureApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum BiometricType: Int {
  case face = 0
  case fingerprint = 1
  case iris = 2
  case weak = 3
  case strong = 4
  case unavailable = 5
}

/// Standardized error codes for the plugin.
enum BiometricError: Int {
  /// The operation was successful.
  case success = 0
  /// The user canceled the operation.
  case userCanceled = 1
  /// The system canceled the operation (e.g. another app took focus).
  case systemCanceled = 2
  /// Biometric authentication is not available on this device.
  case notAvailable = 3
  /// No biometrics are enrolled.
  case notEnrolled = 4
  /// The user has not set a passcode/PIN.
  case passcodeNotSet = 5
  /// The user is temporarily locked out due to too many failed attempts.
  case lockedOut = 6
  /// The user is permanently locked out until they log in with a strong method.
  case lockedOutPermanent = 7
  /// The requested key was not found.
  case keyNotFound = 8
  /// The key has been invalidated (e.g. by new biometric enrollment).
  case keyInvalidated = 9
  /// An unknown error occurred.
  case unknown = 10
  /// The input payload was invalid (e.g. not valid Base64).
  case invalidInput = 11
}

enum SignatureType: Int {
  case rsa = 0
  case ecdsa = 1
}

enum KeyFormat: Int {
  case base64 = 0
  case pem = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct BiometricAvailability: Hashable {
  var canAuthenticate: Bool
  var hasEnrolledBiometrics: Bool
  var availableBiometrics: [BiometricType?]
  var reason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricAvailability? {
    let canAuthenticate = pigeonVar_list[0] as! Bool
    let hasEnrolledBiometrics = pigeonVar_list[1] as! Bool
    let availableBiometrics = pigeonVar_list[2] as! [BiometricType?]
    let reason: String? = nilOrValue(pigeonVar_list[3])

    return BiometricAvailability(
      canAuthenticate: canAuthenticate,
      hasEnrolledBiometrics: hasEnrolledBiometrics,
      availableBiometrics: availableBiometrics,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    ]
  }
  static func == (lhs: BiometricAvailability, rhs: BiometricAvailability) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KeyCreationResult: Hashable {
  var publicKey: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeyCreationResult? {
    let publicKey: String? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])
    let code: BiometricError? = nilOrValue(pigeonVar_list[2])

    return KeyCreationResult(
      publicKey: publicKey,
      error: error,
      code: code
    )
  }
  func toList() -> [Any?] {
    return [
      publicKey,
      error,
      code,
    ]
  }
  static func == (lhs: KeyCreationResult, rhs: KeyCreationResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SignatureResult: Hashable {
  var signature: String? = nil
  var publicKey: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SignatureResult? {
    let signature: String? = nilOrValue(pigeonVar_list[0])
    let publicKey: String? = nilOrValue(pigeonVar_list[1])
    let error: String? = nilOrValue(pigeonVar_list[2])
    let code: BiometricError? = nilOrValue(pigeonVar_list[3])

    return SignatureResult(
      signature: signature,
      publicKey: publicKey,
      error: error,
      code: code
    )
  }
  func toList() -> [Any?] {
    return [
      signature,
      publicKey,
      error,
      code,
    ]
  }
  static func == (lhs: SignatureResult, rhs: SignatureResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DecryptResult: Hashable {
  var decryptedData: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptResult? {
    let decryptedData: String? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])
    let code: BiometricError? = nilOrValue(pigeonVar_list[2])

    return DecryptResult(
      decryptedData: decryptedData,
      error: error,
      code: code
    )
  }
  func toList() -> [Any?] {
    return [
      decryptedData,
      error,
      code,
    ]
  }
  static func == (lhs: DecryptResult, rhs: DecryptResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for Android.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidConfig: Hashable {
  var useDeviceCredentials: Bool? = nil
  var setInvalidatedByBiometricEnrollment: Bool? = nil
  var enableDecryption: Bool? = nil
  var signatureType: SignatureType? = nil
  var promptTitle: String? = nil
  var promptSubtitle: String? = nil
  var promptDescription: String? = nil
  var cancelButtonText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidConfig? {
    let useDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[0])
    let setInvalidatedByBiometricEnrollment: Bool? = nilOrValue(pigeonVar_list[1])
    let enableDecryption: Bool? = nilOrValue(pigeonVar_list[2])
    let signatureType: SignatureType? = nilOrValue(pigeonVar_list[3])
    let promptTitle: String? = nilOrValue(pigeonVar_list[4])
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[5])
    let promptDescription: String? = nilOrValue(pigeonVar_list[6])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[7])

    return AndroidConfig(
      useDeviceCredentials: useDeviceCredentials,
      setInvalidatedByBiometricEnrollment: setInvalidatedByBiometricEnrollment,
      enableDecryption: enableDecryption,
      signatureType: signatureType,
      promptTitle: promptTitle,
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText
    )
  }
  func toList() -> [Any?] {
    return [
      useDeviceCredentials,
      setInvalidatedByBiometricEnrollment,
      enableDecryption,
      signatureType,
      promptTitle,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    ]
  }
  static func == (lhs: AndroidConfig, rhs: AndroidConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for iOS.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IosConfig: Hashable {
  var useDeviceCredentials: Bool? = nil
  var biometryCurrentSet: Bool? = nil
  var signatureType: SignatureType? = nil
  var localizedReason: String? = nil
  var shouldMigrate: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosConfig? {
    let useDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[0])
    let biometryCurrentSet: Bool? = nilOrValue(pigeonVar_list[1])
    let signatureType: SignatureType? = nilOrValue(pigeonVar_list[2])
    let localizedReason: String? = nilOrValue(pigeonVar_list[3])
    let shouldMigrate: Bool? = nilOrValue(pigeonVar_list[4])

    return IosConfig(
      useDeviceCredentials: useDeviceCredentials,
      biometryCurrentSet: biometryCurrentSet,
      signatureType: signatureType,
      localizedReason: localizedReason,
      shouldMigrate: shouldMigrate
    )
  }
  func toList() -> [Any?] {
    return [
      useDeviceCredentials,
      biometryCurrentSet,
      signatureType,
      localizedReason,
      shouldMigrate,
    ]
  }
  static func == (lhs: IosConfig, rhs: IosConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for macOS.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MacosConfig: Hashable {
  var useDeviceCredentials: Bool? = nil
  var biometryCurrentSet: Bool? = nil
  var signatureType: SignatureType? = nil
  var localizedReason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MacosConfig? {
    let useDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[0])
    let biometryCurrentSet: Bool? = nilOrValue(pigeonVar_list[1])
    let signatureType: SignatureType? = nilOrValue(pigeonVar_list[2])
    let localizedReason: String? = nilOrValue(pigeonVar_list[3])

    return MacosConfig(
      useDeviceCredentials: useDeviceCredentials,
      biometryCurrentSet: biometryCurrentSet,
      signatureType: signatureType,
      localizedReason: localizedReason
    )
  }
  func toList() -> [Any?] {
    return [
      useDeviceCredentials,
      biometryCurrentSet,
      signatureType,
      localizedReason,
    ]
  }
  static func == (lhs: MacosConfig, rhs: MacosConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

private class BiometricSignatureApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricError(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SignatureType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KeyFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return BiometricAvailability.fromList(self.readValue() as! [Any?])
    case 134:
      return KeyCreationResult.fromList(self.readValue() as! [Any?])
    case 135:
      return SignatureResult.fromList(self.readValue() as! [Any?])
    case 136:
      return DecryptResult.fromList(self.readValue() as! [Any?])
    case 137:
      return AndroidConfig.fromList(self.readValue() as! [Any?])
    case 138:
      return IosConfig.fromList(self.readValue() as! [Any?])
    case 139:
      return MacosConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BiometricSignatureApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BiometricType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricError {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? SignatureType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? KeyFormat {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricAvailability {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? KeyCreationResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? SignatureResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidConfig {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? IosConfig {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? MacosConfig {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BiometricSignatureApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BiometricSignatureApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BiometricSignatureApiPigeonCodecWriter(data: data)
  }
}

class BiometricSignatureApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BiometricSignatureApiPigeonCodec(readerWriter: BiometricSignatureApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BiometricSignatureApi {
  /// Checks if biometric authentication is available.
  func getBiometricAvailability() throws -> BiometricAvailability
  /// Creates a new key pair.
  func createKeys(androidConfig: AndroidConfig?, iosConfig: IosConfig?, macosConfig: MacosConfig?, keyFormat: KeyFormat, enforceBiometric: Bool, promptMessage: String?, completion: @escaping (Result<KeyCreationResult, Error>) -> Void)
  /// Creates a signature.
  func createSignature(payload: String?, androidConfig: AndroidConfig?, iosConfig: IosConfig?, macosConfig: MacosConfig?, promptMessage: String?, completion: @escaping (Result<SignatureResult, Error>) -> Void)
  /// Decrypts data.
  func decrypt(payload: String?, androidConfig: AndroidConfig?, iosConfig: IosConfig?, macosConfig: MacosConfig?, promptMessage: String?, completion: @escaping (Result<DecryptResult, Error>) -> Void)
  /// Deletes keys.
  func deleteKeys() throws -> Bool
  /// Checks if a key exists.
  func biometricKeyExists(checkValidity: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BiometricSignatureApiSetup {
  static var codec: FlutterStandardMessageCodec { BiometricSignatureApiPigeonCodec.shared }
  /// Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Checks if biometric authentication is available.
    let getBiometricAvailabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getBiometricAvailability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBiometricAvailabilityChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBiometricAvailability()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBiometricAvailabilityChannel.setMessageHandler(nil)
    }
    /// Creates a new key pair.
    let createKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let androidConfigArg: AndroidConfig? = nilOrValue(args[0])
        let iosConfigArg: IosConfig? = nilOrValue(args[1])
        let macosConfigArg: MacosConfig? = nilOrValue(args[2])
        let keyFormatArg = args[3] as! KeyFormat
        let enforceBiometricArg = args[4] as! Bool
        let promptMessageArg: String? = nilOrValue(args[5])
        api.createKeys(androidConfig: androidConfigArg, iosConfig: iosConfigArg, macosConfig: macosConfigArg, keyFormat: keyFormatArg, enforceBiometric: enforceBiometricArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createKeysChannel.setMessageHandler(nil)
    }
    /// Creates a signature.
    let createSignatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSignatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg: String? = nilOrValue(args[0])
        let androidConfigArg: AndroidConfig? = nilOrValue(args[1])
        let iosConfigArg: IosConfig? = nilOrValue(args[2])
        let macosConfigArg: MacosConfig? = nilOrValue(args[3])
        let promptMessageArg: String? = nilOrValue(args[4])
        api.createSignature(payload: payloadArg, androidConfig: androidConfigArg, iosConfig: iosConfigArg, macosConfig: macosConfigArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSignatureChannel.setMessageHandler(nil)
    }
    /// Decrypts data.
    let decryptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decryptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg: String? = nilOrValue(args[0])
        let androidConfigArg: AndroidConfig? = nilOrValue(args[1])
        let iosConfigArg: IosConfig? = nilOrValue(args[2])
        let macosConfigArg: MacosConfig? = nilOrValue(args[3])
        let promptMessageArg: String? = nilOrValue(args[4])
        api.decrypt(payload: payloadArg, androidConfig: androidConfigArg, iosConfig: iosConfigArg, macosConfig: macosConfigArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      decryptChannel.setMessageHandler(nil)
    }
    /// Deletes keys.
    let deleteKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteKeysChannel.setMessageHandler { _, reply in
        do {
          let result = try api.deleteKeys()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteKeysChannel.setMessageHandler(nil)
    }
    /// Checks if a key exists.
    let biometricKeyExistsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricKeyExists\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      biometricKeyExistsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let checkValidityArg = args[0] as! Bool
        api.biometricKeyExists(checkValidity: checkValidityArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      biometricKeyExistsChannel.setMessageHandler(nil)
    }
  }
}
