// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.visionflutter.biometric_signature

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BiometricSignatureApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Types of biometric authentication supported by the device. */
enum class BiometricType(val raw: Int) {
  /** Face recognition (Face ID on iOS, face unlock on Android). */
  FACE(0),
  /** Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android). */
  FINGERPRINT(1),
  /** Iris scanner (Android only, rare on consumer devices). */
  IRIS(2),
  /** Multiple biometric types are available on the device. */
  MULTIPLE(3),
  /** No biometric hardware available or biometrics are disabled. */
  UNAVAILABLE(4);

  companion object {
    fun ofRaw(raw: Int): BiometricType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Standardized error codes for the plugin. */
enum class BiometricError(val raw: Int) {
  /** The operation was successful. */
  SUCCESS(0),
  /** The user canceled the operation. */
  USER_CANCELED(1),
  /** Biometric authentication is not available on this device. */
  NOT_AVAILABLE(2),
  /** No biometrics are enrolled. */
  NOT_ENROLLED(3),
  /** The user is temporarily locked out due to too many failed attempts. */
  LOCKED_OUT(4),
  /** The user is permanently locked out until they log in with a strong method. */
  LOCKED_OUT_PERMANENT(5),
  /** The requested key was not found. */
  KEY_NOT_FOUND(6),
  /** The key has been invalidated (e.g. by new biometric enrollment). */
  KEY_INVALIDATED(7),
  /** An unknown error occurred. */
  UNKNOWN(8),
  /** The input payload was invalid (e.g. not valid Base64). */
  INVALID_INPUT(9);

  companion object {
    fun ofRaw(raw: Int): BiometricError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The cryptographic algorithm to use for key generation. */
enum class SignatureType(val raw: Int) {
  /** RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC). */
  RSA(0),
  /** ECDSA P-256 (hardware-backed on all platforms). */
  ECDSA(1);

  companion object {
    fun ofRaw(raw: Int): SignatureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Output format for public keys. */
enum class KeyFormat(val raw: Int) {
  /** Base64-encoded DER (SubjectPublicKeyInfo). */
  BASE64(0),
  /** PEM format with BEGIN/END PUBLIC KEY headers. */
  PEM(1),
  /** Hexadecimal-encoded DER. */
  HEX(2),
  /** Raw DER bytes (returned via `publicKeyBytes`). */
  RAW(3);

  companion object {
    fun ofRaw(raw: Int): KeyFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Output format for cryptographic signatures. */
enum class SignatureFormat(val raw: Int) {
  /** Base64-encoded signature bytes. */
  BASE64(0),
  /** Hexadecimal-encoded signature bytes. */
  HEX(1),
  /** Raw signature bytes (returned via `signatureBytes`). */
  RAW(2);

  companion object {
    fun ofRaw(raw: Int): SignatureFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Input format for encrypted payloads to decrypt. */
enum class PayloadFormat(val raw: Int) {
  /** Base64-encoded ciphertext. */
  BASE64(0),
  /** Hexadecimal-encoded ciphertext. */
  HEX(1),
  /** Raw UTF-8 string (not recommended for binary data). */
  RAW(2);

  companion object {
    fun ofRaw(raw: Int): PayloadFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BiometricAvailability (
  val canAuthenticate: Boolean,
  val hasEnrolledBiometrics: Boolean,
  val availableBiometrics: List<BiometricType?>,
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricAvailability {
      val canAuthenticate = pigeonVar_list[0] as Boolean
      val hasEnrolledBiometrics = pigeonVar_list[1] as Boolean
      val availableBiometrics = pigeonVar_list[2] as List<BiometricType?>
      val reason = pigeonVar_list[3] as String?
      return BiometricAvailability(canAuthenticate, hasEnrolledBiometrics, availableBiometrics, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BiometricAvailability) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KeyCreationResult (
  val publicKey: String? = null,
  val publicKeyBytes: ByteArray? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  val algorithm: String? = null,
  val keySize: Long? = null,
  val decryptingPublicKey: String? = null,
  val decryptingAlgorithm: String? = null,
  val decryptingKeySize: Long? = null,
  val isHybridMode: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyCreationResult {
      val publicKey = pigeonVar_list[0] as String?
      val publicKeyBytes = pigeonVar_list[1] as ByteArray?
      val error = pigeonVar_list[2] as String?
      val code = pigeonVar_list[3] as BiometricError?
      val algorithm = pigeonVar_list[4] as String?
      val keySize = pigeonVar_list[5] as Long?
      val decryptingPublicKey = pigeonVar_list[6] as String?
      val decryptingAlgorithm = pigeonVar_list[7] as String?
      val decryptingKeySize = pigeonVar_list[8] as Long?
      val isHybridMode = pigeonVar_list[9] as Boolean?
      return KeyCreationResult(publicKey, publicKeyBytes, error, code, algorithm, keySize, decryptingPublicKey, decryptingAlgorithm, decryptingKeySize, isHybridMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KeyCreationResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SignatureResult (
  val signature: String? = null,
  val signatureBytes: ByteArray? = null,
  val publicKey: String? = null,
  val error: String? = null,
  val code: BiometricError? = null,
  val algorithm: String? = null,
  val keySize: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignatureResult {
      val signature = pigeonVar_list[0] as String?
      val signatureBytes = pigeonVar_list[1] as ByteArray?
      val publicKey = pigeonVar_list[2] as String?
      val error = pigeonVar_list[3] as String?
      val code = pigeonVar_list[4] as BiometricError?
      val algorithm = pigeonVar_list[5] as String?
      val keySize = pigeonVar_list[6] as Long?
      return SignatureResult(signature, signatureBytes, publicKey, error, code, algorithm, keySize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SignatureResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptResult (
  val decryptedData: String? = null,
  val error: String? = null,
  val code: BiometricError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptResult {
      val decryptedData = pigeonVar_list[0] as String?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      return DecryptResult(decryptedData, error, code)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      decryptedData,
      error,
      code,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DecryptResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for Android key creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidCreateKeysConfig (
  val enableDecryption: Boolean? = null,
  val promptSubtitle: String? = null,
  val promptDescription: String? = null,
  val cancelButtonText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidCreateKeysConfig {
      val enableDecryption = pigeonVar_list[0] as Boolean?
      val promptSubtitle = pigeonVar_list[1] as String?
      val promptDescription = pigeonVar_list[2] as String?
      val cancelButtonText = pigeonVar_list[3] as String?
      return AndroidCreateKeysConfig(enableDecryption, promptSubtitle, promptDescription, cancelButtonText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AndroidCreateKeysConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for iOS key creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosCreateKeysConfig (
  val reserved: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosCreateKeysConfig {
      val reserved = pigeonVar_list[0] as String?
      return IosCreateKeysConfig(reserved)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reserved,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is IosCreateKeysConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for macOS key creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MacosCreateKeysConfig (
  val reserved: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MacosCreateKeysConfig {
      val reserved = pigeonVar_list[0] as String?
      return MacosCreateKeysConfig(reserved)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reserved,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MacosCreateKeysConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for Android signature creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidCreateSignatureConfig (
  val promptSubtitle: String? = null,
  val promptDescription: String? = null,
  val cancelButtonText: String? = null,
  val allowDeviceCredentials: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidCreateSignatureConfig {
      val promptSubtitle = pigeonVar_list[0] as String?
      val promptDescription = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      return AndroidCreateSignatureConfig(promptSubtitle, promptDescription, cancelButtonText, allowDeviceCredentials)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AndroidCreateSignatureConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for iOS signature creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosCreateSignatureConfig (
  val shouldMigrate: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosCreateSignatureConfig {
      val shouldMigrate = pigeonVar_list[0] as Boolean?
      return IosCreateSignatureConfig(shouldMigrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      shouldMigrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is IosCreateSignatureConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for macOS signature creation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MacosCreateSignatureConfig (
  val reserved: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MacosCreateSignatureConfig {
      val reserved = pigeonVar_list[0] as String?
      return MacosCreateSignatureConfig(reserved)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reserved,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MacosCreateSignatureConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for Android decryption.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidDecryptConfig (
  val promptSubtitle: String? = null,
  val promptDescription: String? = null,
  val cancelButtonText: String? = null,
  val allowDeviceCredentials: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidDecryptConfig {
      val promptSubtitle = pigeonVar_list[0] as String?
      val promptDescription = pigeonVar_list[1] as String?
      val cancelButtonText = pigeonVar_list[2] as String?
      val allowDeviceCredentials = pigeonVar_list[3] as Boolean?
      return AndroidDecryptConfig(promptSubtitle, promptDescription, cancelButtonText, allowDeviceCredentials)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AndroidDecryptConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for iOS decryption.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosDecryptConfig (
  val shouldMigrate: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosDecryptConfig {
      val shouldMigrate = pigeonVar_list[0] as Boolean?
      return IosDecryptConfig(shouldMigrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      shouldMigrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is IosDecryptConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for macOS decryption.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MacosDecryptConfig (
  val reserved: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MacosDecryptConfig {
      val reserved = pigeonVar_list[0] as String?
      return MacosDecryptConfig(reserved)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reserved,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MacosDecryptConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class BiometricSignatureApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricError.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyFormat.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureFormat.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PayloadFormat.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricAvailability.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyCreationResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignatureResult.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidCreateKeysConfig.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosCreateKeysConfig.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MacosCreateKeysConfig.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidCreateSignatureConfig.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosCreateSignatureConfig.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MacosCreateSignatureConfig.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidDecryptConfig.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosDecryptConfig.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MacosDecryptConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BiometricType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricError -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SignatureType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is KeyFormat -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is SignatureFormat -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is PayloadFormat -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricAvailability -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is KeyCreationResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is SignatureResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is DecryptResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is AndroidCreateKeysConfig -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is IosCreateKeysConfig -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is MacosCreateKeysConfig -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is AndroidCreateSignatureConfig -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is IosCreateSignatureConfig -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is MacosCreateSignatureConfig -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is AndroidDecryptConfig -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is IosDecryptConfig -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is MacosDecryptConfig -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BiometricSignatureApi {
  /** Checks if biometric authentication is available. */
  fun biometricAuthAvailable(): BiometricAvailability
  /** Creates a new key pair. */
  fun createKeys(androidConfig: AndroidCreateKeysConfig?, iosConfig: IosCreateKeysConfig?, macosConfig: MacosCreateKeysConfig?, useDeviceCredentials: Boolean?, signatureType: SignatureType?, setInvalidatedByBiometricEnrollment: Boolean?, keyFormat: KeyFormat, enforceBiometric: Boolean, promptMessage: String?, callback: (Result<KeyCreationResult>) -> Unit)
  /** Creates a signature. */
  fun createSignature(payload: String, androidConfig: AndroidCreateSignatureConfig?, iosConfig: IosCreateSignatureConfig?, macosConfig: MacosCreateSignatureConfig?, signatureFormat: SignatureFormat, keyFormat: KeyFormat, promptMessage: String?, callback: (Result<SignatureResult>) -> Unit)
  /** Decrypts data. */
  fun decrypt(payload: String, payloadFormat: PayloadFormat, androidConfig: AndroidDecryptConfig?, iosConfig: IosDecryptConfig?, macosConfig: MacosDecryptConfig?, promptMessage: String?, callback: (Result<DecryptResult>) -> Unit)
  /** Deletes keys. */
  fun deleteKeys(): Boolean
  /** Checks if a key exists. */
  fun biometricKeyExists(checkValidity: Boolean, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by BiometricSignatureApi. */
    val codec: MessageCodec<Any?> by lazy {
      BiometricSignatureApiPigeonCodec()
    }
    /** Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.biometricAuthAvailable())
            } catch (exception: Throwable) {
              BiometricSignatureApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val androidConfigArg = args[0] as AndroidCreateKeysConfig?
            val iosConfigArg = args[1] as IosCreateKeysConfig?
            val macosConfigArg = args[2] as MacosCreateKeysConfig?
            val useDeviceCredentialsArg = args[3] as Boolean?
            val signatureTypeArg = args[4] as SignatureType?
            val setInvalidatedByBiometricEnrollmentArg = args[5] as Boolean?
            val keyFormatArg = args[6] as KeyFormat
            val enforceBiometricArg = args[7] as Boolean
            val promptMessageArg = args[8] as String?
            api.createKeys(androidConfigArg, iosConfigArg, macosConfigArg, useDeviceCredentialsArg, signatureTypeArg, setInvalidatedByBiometricEnrollmentArg, keyFormatArg, enforceBiometricArg, promptMessageArg) { result: Result<KeyCreationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String
            val androidConfigArg = args[1] as AndroidCreateSignatureConfig?
            val iosConfigArg = args[2] as IosCreateSignatureConfig?
            val macosConfigArg = args[3] as MacosCreateSignatureConfig?
            val signatureFormatArg = args[4] as SignatureFormat
            val keyFormatArg = args[5] as KeyFormat
            val promptMessageArg = args[6] as String?
            api.createSignature(payloadArg, androidConfigArg, iosConfigArg, macosConfigArg, signatureFormatArg, keyFormatArg, promptMessageArg) { result: Result<SignatureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String
            val payloadFormatArg = args[1] as PayloadFormat
            val androidConfigArg = args[2] as AndroidDecryptConfig?
            val iosConfigArg = args[3] as IosDecryptConfig?
            val macosConfigArg = args[4] as MacosDecryptConfig?
            val promptMessageArg = args[5] as String?
            api.decrypt(payloadArg, payloadFormatArg, androidConfigArg, iosConfigArg, macosConfigArg, promptMessageArg) { result: Result<DecryptResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.deleteKeys())
            } catch (exception: Throwable) {
              BiometricSignatureApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricKeyExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val checkValidityArg = args[0] as Boolean
            api.biometricKeyExists(checkValidityArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
