// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.visionflutter.biometric_signature

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BiometricSignatureApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BiometricType(val raw: Int) {
  FACE(0),
  FINGERPRINT(1),
  IRIS(2),
  WEAK(3),
  STRONG(4),
  UNAVAILABLE(5);

  companion object {
    fun ofRaw(raw: Int): BiometricType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Standardized error codes for the plugin. */
enum class BiometricError(val raw: Int) {
  /** The operation was successful. */
  SUCCESS(0),
  /** The user canceled the operation. */
  USER_CANCELED(1),
  /** The system canceled the operation (e.g. another app took focus). */
  SYSTEM_CANCELED(2),
  /** Biometric authentication is not available on this device. */
  NOT_AVAILABLE(3),
  /** No biometrics are enrolled. */
  NOT_ENROLLED(4),
  /** The user has not set a passcode/PIN. */
  PASSCODE_NOT_SET(5),
  /** The user is temporarily locked out due to too many failed attempts. */
  LOCKED_OUT(6),
  /** The user is permanently locked out until they log in with a strong method. */
  LOCKED_OUT_PERMANENT(7),
  /** The requested key was not found. */
  KEY_NOT_FOUND(8),
  /** The key has been invalidated (e.g. by new biometric enrollment). */
  KEY_INVALIDATED(9),
  /** An unknown error occurred. */
  UNKNOWN(10),
  /** The input payload was invalid (e.g. not valid Base64). */
  INVALID_INPUT(11);

  companion object {
    fun ofRaw(raw: Int): BiometricError? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SignatureType(val raw: Int) {
  RSA(0),
  ECDSA(1);

  companion object {
    fun ofRaw(raw: Int): SignatureType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class KeyFormat(val raw: Int) {
  BASE64(0),
  PEM(1);

  companion object {
    fun ofRaw(raw: Int): KeyFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BiometricAvailability (
  val canAuthenticate: Boolean,
  val hasEnrolledBiometrics: Boolean,
  val availableBiometrics: List<BiometricType?>,
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BiometricAvailability {
      val canAuthenticate = pigeonVar_list[0] as Boolean
      val hasEnrolledBiometrics = pigeonVar_list[1] as Boolean
      val availableBiometrics = pigeonVar_list[2] as List<BiometricType?>
      val reason = pigeonVar_list[3] as String?
      return BiometricAvailability(canAuthenticate, hasEnrolledBiometrics, availableBiometrics, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is BiometricAvailability) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class KeyCreationResult (
  val publicKey: String? = null,
  val error: String? = null,
  val code: BiometricError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyCreationResult {
      val publicKey = pigeonVar_list[0] as String?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      return KeyCreationResult(publicKey, error, code)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      publicKey,
      error,
      code,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is KeyCreationResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SignatureResult (
  val signature: String? = null,
  val publicKey: String? = null,
  val error: String? = null,
  val code: BiometricError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignatureResult {
      val signature = pigeonVar_list[0] as String?
      val publicKey = pigeonVar_list[1] as String?
      val error = pigeonVar_list[2] as String?
      val code = pigeonVar_list[3] as BiometricError?
      return SignatureResult(signature, publicKey, error, code)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      signature,
      publicKey,
      error,
      code,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SignatureResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DecryptResult (
  val decryptedData: String? = null,
  val error: String? = null,
  val code: BiometricError? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DecryptResult {
      val decryptedData = pigeonVar_list[0] as String?
      val error = pigeonVar_list[1] as String?
      val code = pigeonVar_list[2] as BiometricError?
      return DecryptResult(decryptedData, error, code)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      decryptedData,
      error,
      code,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DecryptResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AndroidConfig (
  val useDeviceCredentials: Boolean? = null,
  val setInvalidatedByBiometricEnrollment: Boolean? = null,
  val enableDecryption: Boolean? = null,
  val signatureType: SignatureType? = null,
  val promptTitle: String? = null,
  val promptSubtitle: String? = null,
  val promptDescription: String? = null,
  val cancelButtonText: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidConfig {
      val useDeviceCredentials = pigeonVar_list[0] as Boolean?
      val setInvalidatedByBiometricEnrollment = pigeonVar_list[1] as Boolean?
      val enableDecryption = pigeonVar_list[2] as Boolean?
      val signatureType = pigeonVar_list[3] as SignatureType?
      val promptTitle = pigeonVar_list[4] as String?
      val promptSubtitle = pigeonVar_list[5] as String?
      val promptDescription = pigeonVar_list[6] as String?
      val cancelButtonText = pigeonVar_list[7] as String?
      return AndroidConfig(useDeviceCredentials, setInvalidatedByBiometricEnrollment, enableDecryption, signatureType, promptTitle, promptSubtitle, promptDescription, cancelButtonText)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      useDeviceCredentials,
      setInvalidatedByBiometricEnrollment,
      enableDecryption,
      signatureType,
      promptTitle,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AndroidConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for iOS.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IosConfig (
  val useDeviceCredentials: Boolean? = null,
  val biometryCurrentSet: Boolean? = null,
  val signatureType: SignatureType? = null,
  val localizedReason: String? = null,
  val shouldMigrate: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosConfig {
      val useDeviceCredentials = pigeonVar_list[0] as Boolean?
      val biometryCurrentSet = pigeonVar_list[1] as Boolean?
      val signatureType = pigeonVar_list[2] as SignatureType?
      val localizedReason = pigeonVar_list[3] as String?
      val shouldMigrate = pigeonVar_list[4] as Boolean?
      return IosConfig(useDeviceCredentials, biometryCurrentSet, signatureType, localizedReason, shouldMigrate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      useDeviceCredentials,
      biometryCurrentSet,
      signatureType,
      localizedReason,
      shouldMigrate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is IosConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Configuration for macOS.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MacosConfig (
  val useDeviceCredentials: Boolean? = null,
  val biometryCurrentSet: Boolean? = null,
  val signatureType: SignatureType? = null,
  val localizedReason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MacosConfig {
      val useDeviceCredentials = pigeonVar_list[0] as Boolean?
      val biometryCurrentSet = pigeonVar_list[1] as Boolean?
      val signatureType = pigeonVar_list[2] as SignatureType?
      val localizedReason = pigeonVar_list[3] as String?
      return MacosConfig(useDeviceCredentials, biometryCurrentSet, signatureType, localizedReason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      useDeviceCredentials,
      biometryCurrentSet,
      signatureType,
      localizedReason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MacosConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return BiometricSignatureApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class BiometricSignatureApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BiometricError.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SignatureType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyFormat.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BiometricAvailability.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyCreationResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignatureResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DecryptResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidConfig.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosConfig.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MacosConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BiometricType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricError -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SignatureType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is KeyFormat -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is BiometricAvailability -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is KeyCreationResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is SignatureResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is DecryptResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is AndroidConfig -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is IosConfig -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is MacosConfig -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BiometricSignatureApi {
  /** Checks if biometric authentication is available. */
  fun getBiometricAvailability(): BiometricAvailability
  /** Creates a new key pair. */
  fun createKeys(androidConfig: AndroidConfig?, iosConfig: IosConfig?, macosConfig: MacosConfig?, keyFormat: KeyFormat, enforceBiometric: Boolean, promptMessage: String?, callback: (Result<KeyCreationResult>) -> Unit)
  /** Creates a signature. */
  fun createSignature(payload: String?, androidConfig: AndroidConfig?, iosConfig: IosConfig?, macosConfig: MacosConfig?, promptMessage: String?, callback: (Result<SignatureResult>) -> Unit)
  /** Decrypts data. */
  fun decrypt(payload: String?, androidConfig: AndroidConfig?, iosConfig: IosConfig?, macosConfig: MacosConfig?, promptMessage: String?, callback: (Result<DecryptResult>) -> Unit)
  /** Deletes keys. */
  fun deleteKeys(): Boolean
  /** Checks if a key exists. */
  fun biometricKeyExists(checkValidity: Boolean, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by BiometricSignatureApi. */
    val codec: MessageCodec<Any?> by lazy {
      BiometricSignatureApiPigeonCodec()
    }
    /** Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getBiometricAvailability$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getBiometricAvailability())
            } catch (exception: Throwable) {
              BiometricSignatureApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val androidConfigArg = args[0] as AndroidConfig?
            val iosConfigArg = args[1] as IosConfig?
            val macosConfigArg = args[2] as MacosConfig?
            val keyFormatArg = args[3] as KeyFormat
            val enforceBiometricArg = args[4] as Boolean
            val promptMessageArg = args[5] as String?
            api.createKeys(androidConfigArg, iosConfigArg, macosConfigArg, keyFormatArg, enforceBiometricArg, promptMessageArg) { result: Result<KeyCreationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String?
            val androidConfigArg = args[1] as AndroidConfig?
            val iosConfigArg = args[2] as IosConfig?
            val macosConfigArg = args[3] as MacosConfig?
            val promptMessageArg = args[4] as String?
            api.createSignature(payloadArg, androidConfigArg, iosConfigArg, macosConfigArg, promptMessageArg) { result: Result<SignatureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val payloadArg = args[0] as String?
            val androidConfigArg = args[1] as AndroidConfig?
            val iosConfigArg = args[2] as IosConfig?
            val macosConfigArg = args[3] as MacosConfig?
            val promptMessageArg = args[4] as String?
            api.decrypt(payloadArg, androidConfigArg, iosConfigArg, macosConfigArg, promptMessageArg) { result: Result<DecryptResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.deleteKeys())
            } catch (exception: Throwable) {
              BiometricSignatureApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricKeyExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val checkValidityArg = args[0] as Boolean
            api.biometricKeyExists(checkValidityArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BiometricSignatureApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BiometricSignatureApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
