// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum BiometricType {
  face,
  fingerprint,
  iris,
  weak,
  strong,
  unavailable,
}

/// Standardized error codes for the plugin.
enum BiometricError {
  /// The operation was successful.
  success,
  /// The user canceled the operation.
  userCanceled,
  /// The system canceled the operation (e.g. another app took focus).
  systemCanceled,
  /// Biometric authentication is not available on this device.
  notAvailable,
  /// No biometrics are enrolled.
  notEnrolled,
  /// The user has not set a passcode/PIN.
  passcodeNotSet,
  /// The user is temporarily locked out due to too many failed attempts.
  lockedOut,
  /// The user is permanently locked out until they log in with a strong method.
  lockedOutPermanent,
  /// The requested key was not found.
  keyNotFound,
  /// The key has been invalidated (e.g. by new biometric enrollment).
  keyInvalidated,
  /// An unknown error occurred.
  unknown,
  /// The input payload was invalid (e.g. not valid Base64).
  invalidInput,
}

enum SignatureType {
  rsa,
  ecdsa,
}

enum KeyFormat {
  base64,
  pem,
}

class BiometricAvailability {
  BiometricAvailability({
    required this.canAuthenticate,
    required this.hasEnrolledBiometrics,
    required this.availableBiometrics,
    this.reason,
  });

  bool canAuthenticate;

  bool hasEnrolledBiometrics;

  List<BiometricType?> availableBiometrics;

  String? reason;

  List<Object?> _toList() {
    return <Object?>[
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    ];
  }

  Object encode() {
    return _toList();  }

  static BiometricAvailability decode(Object result) {
    result as List<Object?>;
    return BiometricAvailability(
      canAuthenticate: result[0]! as bool,
      hasEnrolledBiometrics: result[1]! as bool,
      availableBiometrics: (result[2] as List<Object?>?)!.cast<BiometricType?>(),
      reason: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BiometricAvailability || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class KeyCreationResult {
  KeyCreationResult({
    this.publicKey,
    this.error,
    this.code,
  });

  String? publicKey;

  String? error;

  BiometricError? code;

  List<Object?> _toList() {
    return <Object?>[
      publicKey,
      error,
      code,
    ];
  }

  Object encode() {
    return _toList();  }

  static KeyCreationResult decode(Object result) {
    result as List<Object?>;
    return KeyCreationResult(
      publicKey: result[0] as String?,
      error: result[1] as String?,
      code: result[2] as BiometricError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KeyCreationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SignatureResult {
  SignatureResult({
    this.signature,
    this.publicKey,
    this.error,
    this.code,
  });

  String? signature;

  String? publicKey;

  String? error;

  BiometricError? code;

  List<Object?> _toList() {
    return <Object?>[
      signature,
      publicKey,
      error,
      code,
    ];
  }

  Object encode() {
    return _toList();  }

  static SignatureResult decode(Object result) {
    result as List<Object?>;
    return SignatureResult(
      signature: result[0] as String?,
      publicKey: result[1] as String?,
      error: result[2] as String?,
      code: result[3] as BiometricError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SignatureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class DecryptResult {
  DecryptResult({
    this.decryptedData,
    this.error,
    this.code,
  });

  String? decryptedData;

  String? error;

  BiometricError? code;

  List<Object?> _toList() {
    return <Object?>[
      decryptedData,
      error,
      code,
    ];
  }

  Object encode() {
    return _toList();  }

  static DecryptResult decode(Object result) {
    result as List<Object?>;
    return DecryptResult(
      decryptedData: result[0] as String?,
      error: result[1] as String?,
      code: result[2] as BiometricError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DecryptResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for Android.
class AndroidConfig {
  AndroidConfig({
    this.useDeviceCredentials,
    this.setInvalidatedByBiometricEnrollment,
    this.enableDecryption,
    this.signatureType,
    this.promptTitle,
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
  });

  bool? useDeviceCredentials;

  bool? setInvalidatedByBiometricEnrollment;

  bool? enableDecryption;

  SignatureType? signatureType;

  String? promptTitle;

  String? promptSubtitle;

  String? promptDescription;

  String? cancelButtonText;

  List<Object?> _toList() {
    return <Object?>[
      useDeviceCredentials,
      setInvalidatedByBiometricEnrollment,
      enableDecryption,
      signatureType,
      promptTitle,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidConfig decode(Object result) {
    result as List<Object?>;
    return AndroidConfig(
      useDeviceCredentials: result[0] as bool?,
      setInvalidatedByBiometricEnrollment: result[1] as bool?,
      enableDecryption: result[2] as bool?,
      signatureType: result[3] as SignatureType?,
      promptTitle: result[4] as String?,
      promptSubtitle: result[5] as String?,
      promptDescription: result[6] as String?,
      cancelButtonText: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for iOS.
class IosConfig {
  IosConfig({
    this.useDeviceCredentials,
    this.biometryCurrentSet,
    this.signatureType,
    this.localizedReason,
    this.shouldMigrate,
  });

  bool? useDeviceCredentials;

  bool? biometryCurrentSet;

  SignatureType? signatureType;

  String? localizedReason;

  bool? shouldMigrate;

  List<Object?> _toList() {
    return <Object?>[
      useDeviceCredentials,
      biometryCurrentSet,
      signatureType,
      localizedReason,
      shouldMigrate,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosConfig decode(Object result) {
    result as List<Object?>;
    return IosConfig(
      useDeviceCredentials: result[0] as bool?,
      biometryCurrentSet: result[1] as bool?,
      signatureType: result[2] as SignatureType?,
      localizedReason: result[3] as String?,
      shouldMigrate: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for macOS.
class MacosConfig {
  MacosConfig({
    this.useDeviceCredentials,
    this.biometryCurrentSet,
    this.signatureType,
    this.localizedReason,
  });

  bool? useDeviceCredentials;

  bool? biometryCurrentSet;

  SignatureType? signatureType;

  String? localizedReason;

  List<Object?> _toList() {
    return <Object?>[
      useDeviceCredentials,
      biometryCurrentSet,
      signatureType,
      localizedReason,
    ];
  }

  Object encode() {
    return _toList();  }

  static MacosConfig decode(Object result) {
    result as List<Object?>;
    return MacosConfig(
      useDeviceCredentials: result[0] as bool?,
      biometryCurrentSet: result[1] as bool?,
      signatureType: result[2] as SignatureType?,
      localizedReason: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MacosConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BiometricType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BiometricError) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is SignatureType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is KeyFormat) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is BiometricAvailability) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is KeyCreationResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is SignatureResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is DecryptResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidConfig) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is IosConfig) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is MacosConfig) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricType.values[value];
      case 130: 
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricError.values[value];
      case 131: 
        final value = readValue(buffer) as int?;
        return value == null ? null : SignatureType.values[value];
      case 132: 
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyFormat.values[value];
      case 133: 
        return BiometricAvailability.decode(readValue(buffer)!);
      case 134: 
        return KeyCreationResult.decode(readValue(buffer)!);
      case 135: 
        return SignatureResult.decode(readValue(buffer)!);
      case 136: 
        return DecryptResult.decode(readValue(buffer)!);
      case 137: 
        return AndroidConfig.decode(readValue(buffer)!);
      case 138: 
        return IosConfig.decode(readValue(buffer)!);
      case 139: 
        return MacosConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BiometricSignatureApi {
  /// Constructor for [BiometricSignatureApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BiometricSignatureApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Checks if biometric authentication is available.
  Future<BiometricAvailability> getBiometricAvailability() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getBiometricAvailability$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BiometricAvailability?)!;
    }
  }

  /// Creates a new key pair.
  Future<KeyCreationResult> createKeys(AndroidConfig? androidConfig, IosConfig? iosConfig, MacosConfig? macosConfig, KeyFormat keyFormat, bool enforceBiometric, String? promptMessage) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[androidConfig, iosConfig, macosConfig, keyFormat, enforceBiometric, promptMessage]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KeyCreationResult?)!;
    }
  }

  /// Creates a signature.
  Future<SignatureResult> createSignature(String? payload, AndroidConfig? androidConfig, IosConfig? iosConfig, MacosConfig? macosConfig, String? promptMessage) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[payload, androidConfig, iosConfig, macosConfig, promptMessage]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SignatureResult?)!;
    }
  }

  /// Decrypts data.
  Future<DecryptResult> decrypt(String? payload, AndroidConfig? androidConfig, IosConfig? iosConfig, MacosConfig? macosConfig, String? promptMessage) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[payload, androidConfig, iosConfig, macosConfig, promptMessage]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DecryptResult?)!;
    }
  }

  /// Deletes keys.
  Future<bool> deleteKeys() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Checks if a key exists.
  Future<bool> biometricKeyExists(bool checkValidity) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricKeyExists$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[checkValidity]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}
