// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

/// Types of biometric authentication supported by the device.
enum BiometricType {
  /// Face recognition (Face ID on iOS, face unlock on Android).
  face,

  /// Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android).
  fingerprint,

  /// Iris scanner (Android only, rare on consumer devices).
  iris,

  /// Multiple biometric types are available on the device.
  multiple,

  /// No biometric hardware available or biometrics are disabled.
  unavailable,
}

/// Biometric authentication strength level.
///
/// This affects which biometric sensors can be used for authentication.
/// Note: On iOS/macOS, only strong biometrics are available (Face ID, Touch ID, Optic ID).
/// On Windows, Windows Hello always uses strong authentication.
enum BiometricStrength {
  /// Strong biometrics only (e.g., fingerprint, face recognition with depth sensing).
  /// This is the most secure option and is required for cryptographic operations.
  strong,

  /// Weak biometrics allowed (e.g., face recognition without depth sensing).
  /// This option provides more device compatibility but lower security.
  weak,
}

/// Standardized error codes for the plugin.
enum BiometricError {
  /// The operation was successful.
  success,

  /// The user canceled the operation.
  userCanceled,

  /// Biometric authentication is not available on this device.
  notAvailable,

  /// No biometrics are enrolled.
  notEnrolled,

  /// The user is temporarily locked out due to too many failed attempts.
  lockedOut,

  /// The user is permanently locked out until they log in with a strong method.
  lockedOutPermanent,

  /// The requested key was not found.
  keyNotFound,

  /// The key has been invalidated (e.g. by new biometric enrollment).
  keyInvalidated,

  /// An unknown error occurred.
  unknown,

  /// The input payload was invalid (e.g. not valid Base64).
  invalidInput,

  /// A security update is required before biometrics can be used.
  securityUpdateRequired,

  /// Biometric authentication is not supported on this device/OS version.
  notSupported,

  /// The system canceled the operation (e.g., app went to background).
  systemCanceled,

  /// Failed to show the biometric prompt (e.g., activity not available).
  promptError,
}

/// The cryptographic algorithm to use for key generation.
enum SignatureType {
  /// RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC).
  rsa,

  /// ECDSA P-256 (hardware-backed on all platforms).
  ecdsa,
}

/// Output format for public keys.
enum KeyFormat {
  /// Base64-encoded DER (SubjectPublicKeyInfo).
  base64,

  /// PEM format with BEGIN/END PUBLIC KEY headers.
  pem,

  /// Hexadecimal-encoded DER.
  hex,

  /// Raw DER bytes (returned via `publicKeyBytes`).
  raw,
}

/// Output format for cryptographic signatures.
enum SignatureFormat {
  /// Base64-encoded signature bytes.
  base64,

  /// Hexadecimal-encoded signature bytes.
  hex,

  /// Raw signature bytes (returned via `signatureBytes`).
  raw,
}

/// Input format for encrypted payloads to decrypt.
enum PayloadFormat {
  /// Base64-encoded ciphertext.
  base64,

  /// Hexadecimal-encoded ciphertext.
  hex,

  /// Raw UTF-8 string (not recommended for binary data).
  raw,
}

class BiometricAvailability {
  BiometricAvailability({
    this.canAuthenticate,
    this.hasEnrolledBiometrics,
    this.availableBiometrics,
    this.reason,
  });

  bool? canAuthenticate;

  bool? hasEnrolledBiometrics;

  List<BiometricType?>? availableBiometrics;

  String? reason;

  List<Object?> _toList() {
    return <Object?>[
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static BiometricAvailability decode(Object result) {
    result as List<Object?>;
    return BiometricAvailability(
      canAuthenticate: result[0] as bool?,
      hasEnrolledBiometrics: result[1] as bool?,
      availableBiometrics: (result[2] as List<Object?>?)
          ?.cast<BiometricType?>(),
      reason: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BiometricAvailability || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class KeyCreationResult {
  KeyCreationResult({
    this.publicKey,
    this.publicKeyBytes,
    this.error,
    this.code,
    this.algorithm,
    this.keySize,
    this.decryptingPublicKey,
    this.decryptingAlgorithm,
    this.decryptingKeySize,
    this.isHybridMode,
  });

  String? publicKey;

  Uint8List? publicKeyBytes;

  String? error;

  BiometricError? code;

  String? algorithm;

  int? keySize;

  String? decryptingPublicKey;

  String? decryptingAlgorithm;

  int? decryptingKeySize;

  bool? isHybridMode;

  List<Object?> _toList() {
    return <Object?>[
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KeyCreationResult decode(Object result) {
    result as List<Object?>;
    return KeyCreationResult(
      publicKey: result[0] as String?,
      publicKeyBytes: result[1] as Uint8List?,
      error: result[2] as String?,
      code: result[3] as BiometricError?,
      algorithm: result[4] as String?,
      keySize: result[5] as int?,
      decryptingPublicKey: result[6] as String?,
      decryptingAlgorithm: result[7] as String?,
      decryptingKeySize: result[8] as int?,
      isHybridMode: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KeyCreationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class SignatureResult {
  SignatureResult({
    this.signature,
    this.signatureBytes,
    this.publicKey,
    this.error,
    this.code,
    this.algorithm,
    this.keySize,
  });

  String? signature;

  Uint8List? signatureBytes;

  String? publicKey;

  String? error;

  BiometricError? code;

  String? algorithm;

  int? keySize;

  List<Object?> _toList() {
    return <Object?>[
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SignatureResult decode(Object result) {
    result as List<Object?>;
    return SignatureResult(
      signature: result[0] as String?,
      signatureBytes: result[1] as Uint8List?,
      publicKey: result[2] as String?,
      error: result[3] as String?,
      code: result[4] as BiometricError?,
      algorithm: result[5] as String?,
      keySize: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SignatureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class DecryptResult {
  DecryptResult({this.decryptedData, this.error, this.code});

  String? decryptedData;

  String? error;

  BiometricError? code;

  List<Object?> _toList() {
    return <Object?>[decryptedData, error, code];
  }

  Object encode() {
    return _toList();
  }

  static DecryptResult decode(Object result) {
    result as List<Object?>;
    return DecryptResult(
      decryptedData: result[0] as String?,
      error: result[1] as String?,
      code: result[2] as BiometricError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DecryptResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Detailed information about existing biometric keys.
class KeyInfo {
  KeyInfo({
    this.exists,
    this.isValid,
    this.algorithm,
    this.keySize,
    this.isHybridMode,
    this.publicKey,
    this.decryptingPublicKey,
    this.decryptingAlgorithm,
    this.decryptingKeySize,
  });

  /// Whether any biometric key exists on the device.
  bool? exists;

  /// Whether the key is still valid (not invalidated by biometric changes).
  /// Only populated when `checkValidity: true` is passed.
  bool? isValid;

  /// The algorithm of the signing key (e.g., "RSA", "EC").
  String? algorithm;

  /// The key size in bits (e.g., 2048 for RSA, 256 for EC).
  int? keySize;

  /// Whether the key is in hybrid mode (separate signing and decryption keys).
  bool? isHybridMode;

  /// Signing key public key (formatted according to the requested format).
  String? publicKey;

  /// Decryption key public key for hybrid mode.
  String? decryptingPublicKey;

  /// Algorithm of the decryption key (hybrid mode only).
  String? decryptingAlgorithm;

  /// Key size of the decryption key in bits (hybrid mode only).
  int? decryptingKeySize;

  List<Object?> _toList() {
    return <Object?>[
      exists,
      isValid,
      algorithm,
      keySize,
      isHybridMode,
      publicKey,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KeyInfo decode(Object result) {
    result as List<Object?>;
    return KeyInfo(
      exists: result[0] as bool?,
      isValid: result[1] as bool?,
      algorithm: result[2] as String?,
      keySize: result[3] as int?,
      isHybridMode: result[4] as bool?,
      publicKey: result[5] as String?,
      decryptingPublicKey: result[6] as String?,
      decryptingAlgorithm: result[7] as String?,
      decryptingKeySize: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KeyInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for key creation (all platforms).
///
/// Fields are documented with which platform(s) they apply to.
/// Windows ignores most fields as it only supports RSA with mandatory
/// Windows Hello authentication.
class CreateKeysConfig {
  CreateKeysConfig({
    this.signatureType,
    this.enforceBiometric,
    this.setInvalidatedByBiometricEnrollment,
    this.useDeviceCredentials,
    this.enableDecryption,
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
  });

  /// [Android/iOS/macOS] The cryptographic algorithm to use.
  /// Windows only supports RSA and ignores this field.
  SignatureType? signatureType;

  /// [Android/iOS/macOS] Whether to require biometric authentication
  /// during key creation. Windows always authenticates via Windows Hello.
  bool? enforceBiometric;

  /// [Android/iOS/macOS] Whether to invalidate the key when new biometrics
  /// are enrolled. Not supported on Windows.
  ///
  /// **Security Note**: When `true`, keys become invalid if fingerprints/faces
  /// are added or removed, preventing unauthorized access if an attacker
  /// enrolls their own biometrics on a compromised device.
  bool? setInvalidatedByBiometricEnrollment;

  /// [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
  /// as fallback for biometric authentication. Not supported on Windows.
  bool? useDeviceCredentials;

  /// [Android] Whether to enable decryption capability for the key.
  /// On iOS/macOS, decryption is always available with EC keys.
  bool? enableDecryption;

  /// [Android] Subtitle text for the biometric prompt.
  String? promptSubtitle;

  /// [Android] Description text for the biometric prompt.
  String? promptDescription;

  /// [Android] Text for the cancel button in the biometric prompt.
  String? cancelButtonText;

  List<Object?> _toList() {
    return <Object?>[
      signatureType,
      enforceBiometric,
      setInvalidatedByBiometricEnrollment,
      useDeviceCredentials,
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CreateKeysConfig decode(Object result) {
    result as List<Object?>;
    return CreateKeysConfig(
      signatureType: result[0] as SignatureType?,
      enforceBiometric: result[1] as bool?,
      setInvalidatedByBiometricEnrollment: result[2] as bool?,
      useDeviceCredentials: result[3] as bool?,
      enableDecryption: result[4] as bool?,
      promptSubtitle: result[5] as String?,
      promptDescription: result[6] as String?,
      cancelButtonText: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateKeysConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for signature creation (all platforms).
///
/// Fields are documented with which platform(s) they apply to.
class CreateSignatureConfig {
  CreateSignatureConfig({
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
    this.allowDeviceCredentials,
    this.shouldMigrate,
  });

  /// [Android] Subtitle text for the biometric prompt.
  String? promptSubtitle;

  /// [Android] Description text for the biometric prompt.
  String? promptDescription;

  /// [Android] Text for the cancel button in the biometric prompt.
  String? cancelButtonText;

  /// [Android] Whether to allow device credentials (PIN/pattern) as fallback.
  bool? allowDeviceCredentials;

  /// [iOS] Whether to migrate from legacy keychain storage.
  bool? shouldMigrate;

  List<Object?> _toList() {
    return <Object?>[
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CreateSignatureConfig decode(Object result) {
    result as List<Object?>;
    return CreateSignatureConfig(
      promptSubtitle: result[0] as String?,
      promptDescription: result[1] as String?,
      cancelButtonText: result[2] as String?,
      allowDeviceCredentials: result[3] as bool?,
      shouldMigrate: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateSignatureConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for decryption (all platforms).
///
/// Fields are documented with which platform(s) they apply to.
/// Note: Decryption is not supported on Windows.
class DecryptConfig {
  DecryptConfig({
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
    this.allowDeviceCredentials,
    this.shouldMigrate,
  });

  /// [Android] Subtitle text for the biometric prompt.
  String? promptSubtitle;

  /// [Android] Description text for the biometric prompt.
  String? promptDescription;

  /// [Android] Text for the cancel button in the biometric prompt.
  String? cancelButtonText;

  /// [Android] Whether to allow device credentials (PIN/pattern) as fallback.
  bool? allowDeviceCredentials;

  /// [iOS] Whether to migrate from legacy keychain storage.
  bool? shouldMigrate;

  List<Object?> _toList() {
    return <Object?>[
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
      shouldMigrate,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DecryptConfig decode(Object result) {
    result as List<Object?>;
    return DecryptConfig(
      promptSubtitle: result[0] as String?,
      promptDescription: result[1] as String?,
      cancelButtonText: result[2] as String?,
      allowDeviceCredentials: result[3] as bool?,
      shouldMigrate: result[4] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DecryptConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Configuration for simple biometric prompt (authentication without crypto ops).
///
/// This allows customization of the biometric prompt across platforms.
class SimplePromptConfig {
  SimplePromptConfig({
    this.subtitle,
    this.description,
    this.cancelButtonText,
    this.allowDeviceCredentials,
    this.biometricStrength,
  });

  /// [Android] Subtitle text displayed below the title in the biometric prompt.
  String? subtitle;

  /// [Android] Description text displayed in the biometric prompt body.
  String? description;

  /// [Android] Text for the cancel/negative button.
  /// Default: "Cancel" on Android, system default on iOS/macOS.
  String? cancelButtonText;

  /// [Android/iOS/macOS] Whether to allow device credentials (PIN/pattern/passcode)
  /// as a fallback for biometric authentication.
  ///
  /// When true:
  /// - Android: Shows "Use PIN" option after biometric failure
  /// - iOS/macOS: Uses .deviceOwnerAuthentication policy
  /// - Windows: Not applicable (Windows Hello handles fallback internally)
  ///
  /// Default: false (biometric-only authentication)
  bool? allowDeviceCredentials;

  /// [Android] The required biometric strength level.
  ///
  /// - strong: Only Class 3 biometrics (e.g., fingerprint, in-screen fingerprint)
  /// - weak: Class 2 biometrics allowed (e.g., face unlock without depth)
  ///
  /// Note: iOS/macOS always use strong biometrics. Windows Hello also uses strong.
  /// If strong biometrics are not available but weak are, and strength is set to
  /// strong, authentication will fail with [BiometricError.notEnrolled].
  ///
  /// Default: strong
  BiometricStrength? biometricStrength;

  List<Object?> _toList() {
    return <Object?>[
      subtitle,
      description,
      cancelButtonText,
      allowDeviceCredentials,
      biometricStrength,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SimplePromptConfig decode(Object result) {
    result as List<Object?>;
    return SimplePromptConfig(
      subtitle: result[0] as String?,
      description: result[1] as String?,
      cancelButtonText: result[2] as String?,
      allowDeviceCredentials: result[3] as bool?,
      biometricStrength: result[4] as BiometricStrength?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SimplePromptConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// Result from simple biometric prompt authentication.
class SimplePromptResult {
  SimplePromptResult({this.success, this.error, this.code});

  /// Whether authentication was successful.
  bool? success;

  /// Error message if authentication failed.
  /// This is a human-readable description of what went wrong.
  String? error;

  /// Standardized error code if authentication failed.
  /// Use this for programmatic error handling.
  BiometricError? code;

  List<Object?> _toList() {
    return <Object?>[success, error, code];
  }

  Object encode() {
    return _toList();
  }

  static SimplePromptResult decode(Object result) {
    result as List<Object?>;
    return SimplePromptResult(
      success: result[0] as bool?,
      error: result[1] as String?,
      code: result[2] as BiometricError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SimplePromptResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is BiometricType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is BiometricStrength) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is BiometricError) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is SignatureType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is KeyFormat) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is SignatureFormat) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PayloadFormat) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    } else if (value is BiometricAvailability) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is KeyCreationResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is SignatureResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is DecryptResult) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is KeyInfo) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is CreateKeysConfig) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is CreateSignatureConfig) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is DecryptConfig) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is SimplePromptConfig) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is SimplePromptResult) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricStrength.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricError.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : SignatureType.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyFormat.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : SignatureFormat.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : PayloadFormat.values[value];
      case 136:
        return BiometricAvailability.decode(readValue(buffer)!);
      case 137:
        return KeyCreationResult.decode(readValue(buffer)!);
      case 138:
        return SignatureResult.decode(readValue(buffer)!);
      case 139:
        return DecryptResult.decode(readValue(buffer)!);
      case 140:
        return KeyInfo.decode(readValue(buffer)!);
      case 141:
        return CreateKeysConfig.decode(readValue(buffer)!);
      case 142:
        return CreateSignatureConfig.decode(readValue(buffer)!);
      case 143:
        return DecryptConfig.decode(readValue(buffer)!);
      case 144:
        return SimplePromptConfig.decode(readValue(buffer)!);
      case 145:
        return SimplePromptResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BiometricSignatureApi {
  /// Constructor for [BiometricSignatureApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BiometricSignatureApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Checks if biometric authentication is available.
  Future<BiometricAvailability> biometricAuthAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BiometricAvailability?)!;
    }
  }

  /// Creates a new key pair.
  ///
  /// [config] contains platform-specific options. See [CreateKeysConfig].
  /// [keyFormat] specifies the output format for the public key.
  /// [promptMessage] is the message shown to the user during authentication.
  Future<KeyCreationResult> createKeys(
    CreateKeysConfig? config,
    KeyFormat keyFormat,
    String? promptMessage,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config, keyFormat, promptMessage],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KeyCreationResult?)!;
    }
  }

  /// Creates a signature.
  ///
  /// [payload] is the data to sign.
  /// [config] contains platform-specific options. See [CreateSignatureConfig].
  /// [signatureFormat] specifies the output format for the signature.
  /// [keyFormat] specifies the output format for the public key.
  /// [promptMessage] is the message shown to the user during authentication.
  Future<SignatureResult> createSignature(
    String payload,
    CreateSignatureConfig? config,
    SignatureFormat signatureFormat,
    KeyFormat keyFormat,
    String? promptMessage,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[payload, config, signatureFormat, keyFormat, promptMessage],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SignatureResult?)!;
    }
  }

  /// Decrypts data.
  ///
  /// Note: Not supported on Windows.
  /// [payload] is the encrypted data.
  /// [payloadFormat] specifies the format of the encrypted data.
  /// [config] contains platform-specific options. See [DecryptConfig].
  /// [promptMessage] is the message shown to the user during authentication.
  Future<DecryptResult> decrypt(
    String payload,
    PayloadFormat payloadFormat,
    DecryptConfig? config,
    String? promptMessage,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[payload, payloadFormat, config, promptMessage],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DecryptResult?)!;
    }
  }

  /// Deletes keys.
  Future<bool> deleteKeys() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Gets detailed information about existing biometric keys.
  ///
  /// Returns key metadata including algorithm, size, validity, and public keys.
  Future<KeyInfo> getKeyInfo(bool checkValidity, KeyFormat keyFormat) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getKeyInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[checkValidity, keyFormat],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KeyInfo?)!;
    }
  }

  /// Performs simple biometric authentication without cryptographic operations.
  ///
  /// This is useful for:
  /// - Quick re-authentication flows
  /// - Confirming user presence before sensitive operations
  /// - Simple access control without key management
  ///
  /// [promptMessage] is the main message shown to the user (title on Android).
  /// [config] contains optional platform-specific configuration.
  ///
  /// Returns a [SimplePromptResult] indicating success or failure.
  Future<SimplePromptResult> simplePrompt(
    String promptMessage,
    SimplePromptConfig? config,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.simplePrompt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[promptMessage, config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SimplePromptResult?)!;
    }
  }
}
