// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Types of biometric authentication supported by the device.
enum BiometricType {
  /// Face recognition (Face ID on iOS, face unlock on Android).
  face,
  /// Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android).
  fingerprint,
  /// Iris scanner (Android only, rare on consumer devices).
  iris,
  /// Multiple biometric types are available on the device.
  multiple,
  /// No biometric hardware available or biometrics are disabled.
  unavailable,
}

/// Standardized error codes for the plugin.
enum BiometricError {
  /// The operation was successful.
  success,
  /// The user canceled the operation.
  userCanceled,
  /// Biometric authentication is not available on this device.
  notAvailable,
  /// No biometrics are enrolled.
  notEnrolled,
  /// The user is temporarily locked out due to too many failed attempts.
  lockedOut,
  /// The user is permanently locked out until they log in with a strong method.
  lockedOutPermanent,
  /// The requested key was not found.
  keyNotFound,
  /// The key has been invalidated (e.g. by new biometric enrollment).
  keyInvalidated,
  /// An unknown error occurred.
  unknown,
  /// The input payload was invalid (e.g. not valid Base64).
  invalidInput,
}

/// The cryptographic algorithm to use for key generation.
enum SignatureType {
  /// RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC).
  rsa,
  /// ECDSA P-256 (hardware-backed on all platforms).
  ecdsa,
}

/// Output format for public keys.
enum KeyFormat {
  /// Base64-encoded DER (SubjectPublicKeyInfo).
  base64,
  /// PEM format with BEGIN/END PUBLIC KEY headers.
  pem,
  /// Hexadecimal-encoded DER.
  hex,
  /// Raw DER bytes (returned via `publicKeyBytes`).
  raw,
}

/// Output format for cryptographic signatures.
enum SignatureFormat {
  /// Base64-encoded signature bytes.
  base64,
  /// Hexadecimal-encoded signature bytes.
  hex,
  /// Raw signature bytes (returned via `signatureBytes`).
  raw,
}

/// Input format for encrypted payloads to decrypt.
enum PayloadFormat {
  /// Base64-encoded ciphertext.
  base64,
  /// Hexadecimal-encoded ciphertext.
  hex,
  /// Raw UTF-8 string (not recommended for binary data).
  raw,
}

class BiometricAvailability {
  BiometricAvailability({
    required this.canAuthenticate,
    required this.hasEnrolledBiometrics,
    required this.availableBiometrics,
    this.reason,
  });

  bool canAuthenticate;

  bool hasEnrolledBiometrics;

  List<BiometricType?> availableBiometrics;

  String? reason;

  List<Object?> _toList() {
    return <Object?>[
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    ];
  }

  Object encode() {
    return _toList();  }

  static BiometricAvailability decode(Object result) {
    result as List<Object?>;
    return BiometricAvailability(
      canAuthenticate: result[0]! as bool,
      hasEnrolledBiometrics: result[1]! as bool,
      availableBiometrics: (result[2] as List<Object?>?)!.cast<BiometricType?>(),
      reason: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BiometricAvailability || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class KeyCreationResult {
  KeyCreationResult({
    this.publicKey,
    this.publicKeyBytes,
    this.error,
    this.code,
    this.algorithm,
    this.keySize,
    this.decryptingPublicKey,
    this.decryptingAlgorithm,
    this.decryptingKeySize,
    this.isHybridMode,
  });

  String? publicKey;

  Uint8List? publicKeyBytes;

  String? error;

  BiometricError? code;

  String? algorithm;

  int? keySize;

  String? decryptingPublicKey;

  String? decryptingAlgorithm;

  int? decryptingKeySize;

  bool? isHybridMode;

  List<Object?> _toList() {
    return <Object?>[
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
    ];
  }

  Object encode() {
    return _toList();  }

  static KeyCreationResult decode(Object result) {
    result as List<Object?>;
    return KeyCreationResult(
      publicKey: result[0] as String?,
      publicKeyBytes: result[1] as Uint8List?,
      error: result[2] as String?,
      code: result[3] as BiometricError?,
      algorithm: result[4] as String?,
      keySize: result[5] as int?,
      decryptingPublicKey: result[6] as String?,
      decryptingAlgorithm: result[7] as String?,
      decryptingKeySize: result[8] as int?,
      isHybridMode: result[9] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KeyCreationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SignatureResult {
  SignatureResult({
    this.signature,
    this.signatureBytes,
    this.publicKey,
    this.error,
    this.code,
    this.algorithm,
    this.keySize,
  });

  String? signature;

  Uint8List? signatureBytes;

  String? publicKey;

  String? error;

  BiometricError? code;

  String? algorithm;

  int? keySize;

  List<Object?> _toList() {
    return <Object?>[
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
    ];
  }

  Object encode() {
    return _toList();  }

  static SignatureResult decode(Object result) {
    result as List<Object?>;
    return SignatureResult(
      signature: result[0] as String?,
      signatureBytes: result[1] as Uint8List?,
      publicKey: result[2] as String?,
      error: result[3] as String?,
      code: result[4] as BiometricError?,
      algorithm: result[5] as String?,
      keySize: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SignatureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class DecryptResult {
  DecryptResult({
    this.decryptedData,
    this.error,
    this.code,
  });

  String? decryptedData;

  String? error;

  BiometricError? code;

  List<Object?> _toList() {
    return <Object?>[
      decryptedData,
      error,
      code,
    ];
  }

  Object encode() {
    return _toList();  }

  static DecryptResult decode(Object result) {
    result as List<Object?>;
    return DecryptResult(
      decryptedData: result[0] as String?,
      error: result[1] as String?,
      code: result[2] as BiometricError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DecryptResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for Android key creation.
class AndroidCreateKeysConfig {
  AndroidCreateKeysConfig({
    this.enableDecryption,
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
  });

  bool? enableDecryption;

  String? promptSubtitle;

  String? promptDescription;

  String? cancelButtonText;

  List<Object?> _toList() {
    return <Object?>[
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidCreateKeysConfig decode(Object result) {
    result as List<Object?>;
    return AndroidCreateKeysConfig(
      enableDecryption: result[0] as bool?,
      promptSubtitle: result[1] as String?,
      promptDescription: result[2] as String?,
      cancelButtonText: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidCreateKeysConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for iOS key creation.
class IosCreateKeysConfig {
  IosCreateKeysConfig({
    this.reserved,
  });

  String? reserved;

  List<Object?> _toList() {
    return <Object?>[
      reserved,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosCreateKeysConfig decode(Object result) {
    result as List<Object?>;
    return IosCreateKeysConfig(
      reserved: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosCreateKeysConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for macOS key creation.
class MacosCreateKeysConfig {
  MacosCreateKeysConfig({
    this.reserved,
  });

  String? reserved;

  List<Object?> _toList() {
    return <Object?>[
      reserved,
    ];
  }

  Object encode() {
    return _toList();  }

  static MacosCreateKeysConfig decode(Object result) {
    result as List<Object?>;
    return MacosCreateKeysConfig(
      reserved: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MacosCreateKeysConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for Android signature creation.
class AndroidCreateSignatureConfig {
  AndroidCreateSignatureConfig({
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
    this.allowDeviceCredentials,
  });

  String? promptSubtitle;

  String? promptDescription;

  String? cancelButtonText;

  bool? allowDeviceCredentials;

  List<Object?> _toList() {
    return <Object?>[
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidCreateSignatureConfig decode(Object result) {
    result as List<Object?>;
    return AndroidCreateSignatureConfig(
      promptSubtitle: result[0] as String?,
      promptDescription: result[1] as String?,
      cancelButtonText: result[2] as String?,
      allowDeviceCredentials: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidCreateSignatureConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for iOS signature creation.
class IosCreateSignatureConfig {
  IosCreateSignatureConfig({
    this.shouldMigrate,
  });

  bool? shouldMigrate;

  List<Object?> _toList() {
    return <Object?>[
      shouldMigrate,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosCreateSignatureConfig decode(Object result) {
    result as List<Object?>;
    return IosCreateSignatureConfig(
      shouldMigrate: result[0] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosCreateSignatureConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for macOS signature creation.
class MacosCreateSignatureConfig {
  MacosCreateSignatureConfig({
    this.reserved,
  });

  String? reserved;

  List<Object?> _toList() {
    return <Object?>[
      reserved,
    ];
  }

  Object encode() {
    return _toList();  }

  static MacosCreateSignatureConfig decode(Object result) {
    result as List<Object?>;
    return MacosCreateSignatureConfig(
      reserved: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MacosCreateSignatureConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for Android decryption.
class AndroidDecryptConfig {
  AndroidDecryptConfig({
    this.promptSubtitle,
    this.promptDescription,
    this.cancelButtonText,
    this.allowDeviceCredentials,
  });

  String? promptSubtitle;

  String? promptDescription;

  String? cancelButtonText;

  bool? allowDeviceCredentials;

  List<Object?> _toList() {
    return <Object?>[
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidDecryptConfig decode(Object result) {
    result as List<Object?>;
    return AndroidDecryptConfig(
      promptSubtitle: result[0] as String?,
      promptDescription: result[1] as String?,
      cancelButtonText: result[2] as String?,
      allowDeviceCredentials: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidDecryptConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for iOS decryption.
class IosDecryptConfig {
  IosDecryptConfig({
    this.shouldMigrate,
  });

  bool? shouldMigrate;

  List<Object?> _toList() {
    return <Object?>[
      shouldMigrate,
    ];
  }

  Object encode() {
    return _toList();  }

  static IosDecryptConfig decode(Object result) {
    result as List<Object?>;
    return IosDecryptConfig(
      shouldMigrate: result[0] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IosDecryptConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Configuration for macOS decryption.
class MacosDecryptConfig {
  MacosDecryptConfig({
    this.reserved,
  });

  String? reserved;

  List<Object?> _toList() {
    return <Object?>[
      reserved,
    ];
  }

  Object encode() {
    return _toList();  }

  static MacosDecryptConfig decode(Object result) {
    result as List<Object?>;
    return MacosDecryptConfig(
      reserved: result[0] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MacosDecryptConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is BiometricType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is BiometricError) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is SignatureType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is KeyFormat) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is SignatureFormat) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is PayloadFormat) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is BiometricAvailability) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is KeyCreationResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is SignatureResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is DecryptResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidCreateKeysConfig) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is IosCreateKeysConfig) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is MacosCreateKeysConfig) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidCreateSignatureConfig) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is IosCreateSignatureConfig) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is MacosCreateSignatureConfig) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidDecryptConfig) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is IosDecryptConfig) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is MacosDecryptConfig) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricType.values[value];
      case 130: 
        final value = readValue(buffer) as int?;
        return value == null ? null : BiometricError.values[value];
      case 131: 
        final value = readValue(buffer) as int?;
        return value == null ? null : SignatureType.values[value];
      case 132: 
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyFormat.values[value];
      case 133: 
        final value = readValue(buffer) as int?;
        return value == null ? null : SignatureFormat.values[value];
      case 134: 
        final value = readValue(buffer) as int?;
        return value == null ? null : PayloadFormat.values[value];
      case 135: 
        return BiometricAvailability.decode(readValue(buffer)!);
      case 136: 
        return KeyCreationResult.decode(readValue(buffer)!);
      case 137: 
        return SignatureResult.decode(readValue(buffer)!);
      case 138: 
        return DecryptResult.decode(readValue(buffer)!);
      case 139: 
        return AndroidCreateKeysConfig.decode(readValue(buffer)!);
      case 140: 
        return IosCreateKeysConfig.decode(readValue(buffer)!);
      case 141: 
        return MacosCreateKeysConfig.decode(readValue(buffer)!);
      case 142: 
        return AndroidCreateSignatureConfig.decode(readValue(buffer)!);
      case 143: 
        return IosCreateSignatureConfig.decode(readValue(buffer)!);
      case 144: 
        return MacosCreateSignatureConfig.decode(readValue(buffer)!);
      case 145: 
        return AndroidDecryptConfig.decode(readValue(buffer)!);
      case 146: 
        return IosDecryptConfig.decode(readValue(buffer)!);
      case 147: 
        return MacosDecryptConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BiometricSignatureApi {
  /// Constructor for [BiometricSignatureApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BiometricSignatureApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Checks if biometric authentication is available.
  Future<BiometricAvailability> biometricAuthAvailable() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as BiometricAvailability?)!;
    }
  }

  /// Creates a new key pair.
  Future<KeyCreationResult> createKeys(AndroidCreateKeysConfig? androidConfig, IosCreateKeysConfig? iosConfig, MacosCreateKeysConfig? macosConfig, bool? useDeviceCredentials, SignatureType? signatureType, bool? setInvalidatedByBiometricEnrollment, KeyFormat keyFormat, bool enforceBiometric, String? promptMessage) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[androidConfig, iosConfig, macosConfig, useDeviceCredentials, signatureType, setInvalidatedByBiometricEnrollment, keyFormat, enforceBiometric, promptMessage]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as KeyCreationResult?)!;
    }
  }

  /// Creates a signature.
  Future<SignatureResult> createSignature(String payload, AndroidCreateSignatureConfig? androidConfig, IosCreateSignatureConfig? iosConfig, MacosCreateSignatureConfig? macosConfig, SignatureFormat signatureFormat, KeyFormat keyFormat, String? promptMessage) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[payload, androidConfig, iosConfig, macosConfig, signatureFormat, keyFormat, promptMessage]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SignatureResult?)!;
    }
  }

  /// Decrypts data.
  Future<DecryptResult> decrypt(String payload, PayloadFormat payloadFormat, AndroidDecryptConfig? androidConfig, IosDecryptConfig? iosConfig, MacosDecryptConfig? macosConfig, String? promptMessage) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[payload, payloadFormat, androidConfig, iosConfig, macosConfig, promptMessage]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DecryptResult?)!;
    }
  }

  /// Deletes keys.
  Future<bool> deleteKeys() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Checks if a key exists.
  Future<bool> biometricKeyExists(bool checkValidity) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricKeyExists$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[checkValidity]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}
