// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsBiometricSignatureApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsBiometricSignatureApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsBiometricSignatureApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashBiometricSignatureApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashBiometricSignatureApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashBiometricSignatureApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Types of biometric authentication supported by the device.
enum BiometricType: Int {
  /// Face recognition (Face ID on iOS, face unlock on Android).
  case face = 0
  /// Fingerprint recognition (Touch ID on iOS/macOS, fingerprint on Android).
  case fingerprint = 1
  /// Iris scanner (Android only, rare on consumer devices).
  case iris = 2
  /// Multiple biometric types are available on the device.
  case multiple = 3
  /// No biometric hardware available or biometrics are disabled.
  case unavailable = 4
}

/// Standardized error codes for the plugin.
enum BiometricError: Int {
  /// The operation was successful.
  case success = 0
  /// The user canceled the operation.
  case userCanceled = 1
  /// Biometric authentication is not available on this device.
  case notAvailable = 2
  /// No biometrics are enrolled.
  case notEnrolled = 3
  /// The user is temporarily locked out due to too many failed attempts.
  case lockedOut = 4
  /// The user is permanently locked out until they log in with a strong method.
  case lockedOutPermanent = 5
  /// The requested key was not found.
  case keyNotFound = 6
  /// The key has been invalidated (e.g. by new biometric enrollment).
  case keyInvalidated = 7
  /// An unknown error occurred.
  case unknown = 8
  /// The input payload was invalid (e.g. not valid Base64).
  case invalidInput = 9
}

/// The cryptographic algorithm to use for key generation.
enum SignatureType: Int {
  /// RSA-2048 (Android: native, iOS/macOS: hybrid mode with Secure Enclave EC).
  case rsa = 0
  /// ECDSA P-256 (hardware-backed on all platforms).
  case ecdsa = 1
}

/// Output format for public keys.
enum KeyFormat: Int {
  /// Base64-encoded DER (SubjectPublicKeyInfo).
  case base64 = 0
  /// PEM format with BEGIN/END PUBLIC KEY headers.
  case pem = 1
  /// Hexadecimal-encoded DER.
  case hex = 2
  /// Raw DER bytes (returned via `publicKeyBytes`).
  case raw = 3
}

/// Output format for cryptographic signatures.
enum SignatureFormat: Int {
  /// Base64-encoded signature bytes.
  case base64 = 0
  /// Hexadecimal-encoded signature bytes.
  case hex = 1
  /// Raw signature bytes (returned via `signatureBytes`).
  case raw = 2
}

/// Input format for encrypted payloads to decrypt.
enum PayloadFormat: Int {
  /// Base64-encoded ciphertext.
  case base64 = 0
  /// Hexadecimal-encoded ciphertext.
  case hex = 1
  /// Raw UTF-8 string (not recommended for binary data).
  case raw = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct BiometricAvailability: Hashable {
  var canAuthenticate: Bool? = nil
  var hasEnrolledBiometrics: Bool? = nil
  var availableBiometrics: [BiometricType?]? = nil
  var reason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BiometricAvailability? {
    let canAuthenticate: Bool? = nilOrValue(pigeonVar_list[0])
    let hasEnrolledBiometrics: Bool? = nilOrValue(pigeonVar_list[1])
    let availableBiometrics: [BiometricType?]? = nilOrValue(pigeonVar_list[2])
    let reason: String? = nilOrValue(pigeonVar_list[3])

    return BiometricAvailability(
      canAuthenticate: canAuthenticate,
      hasEnrolledBiometrics: hasEnrolledBiometrics,
      availableBiometrics: availableBiometrics,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      canAuthenticate,
      hasEnrolledBiometrics,
      availableBiometrics,
      reason,
    ]
  }
  static func == (lhs: BiometricAvailability, rhs: BiometricAvailability) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KeyCreationResult: Hashable {
  var publicKey: String? = nil
  var publicKeyBytes: FlutterStandardTypedData? = nil
  var error: String? = nil
  var code: BiometricError? = nil
  var algorithm: String? = nil
  var keySize: Int64? = nil
  var decryptingPublicKey: String? = nil
  var decryptingAlgorithm: String? = nil
  var decryptingKeySize: Int64? = nil
  var isHybridMode: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeyCreationResult? {
    let publicKey: String? = nilOrValue(pigeonVar_list[0])
    let publicKeyBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let error: String? = nilOrValue(pigeonVar_list[2])
    let code: BiometricError? = nilOrValue(pigeonVar_list[3])
    let algorithm: String? = nilOrValue(pigeonVar_list[4])
    let keySize: Int64? = nilOrValue(pigeonVar_list[5])
    let decryptingPublicKey: String? = nilOrValue(pigeonVar_list[6])
    let decryptingAlgorithm: String? = nilOrValue(pigeonVar_list[7])
    let decryptingKeySize: Int64? = nilOrValue(pigeonVar_list[8])
    let isHybridMode: Bool? = nilOrValue(pigeonVar_list[9])

    return KeyCreationResult(
      publicKey: publicKey,
      publicKeyBytes: publicKeyBytes,
      error: error,
      code: code,
      algorithm: algorithm,
      keySize: keySize,
      decryptingPublicKey: decryptingPublicKey,
      decryptingAlgorithm: decryptingAlgorithm,
      decryptingKeySize: decryptingKeySize,
      isHybridMode: isHybridMode
    )
  }
  func toList() -> [Any?] {
    return [
      publicKey,
      publicKeyBytes,
      error,
      code,
      algorithm,
      keySize,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
      isHybridMode,
    ]
  }
  static func == (lhs: KeyCreationResult, rhs: KeyCreationResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SignatureResult: Hashable {
  var signature: String? = nil
  var signatureBytes: FlutterStandardTypedData? = nil
  var publicKey: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil
  var algorithm: String? = nil
  var keySize: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SignatureResult? {
    let signature: String? = nilOrValue(pigeonVar_list[0])
    let signatureBytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[1])
    let publicKey: String? = nilOrValue(pigeonVar_list[2])
    let error: String? = nilOrValue(pigeonVar_list[3])
    let code: BiometricError? = nilOrValue(pigeonVar_list[4])
    let algorithm: String? = nilOrValue(pigeonVar_list[5])
    let keySize: Int64? = nilOrValue(pigeonVar_list[6])

    return SignatureResult(
      signature: signature,
      signatureBytes: signatureBytes,
      publicKey: publicKey,
      error: error,
      code: code,
      algorithm: algorithm,
      keySize: keySize
    )
  }
  func toList() -> [Any?] {
    return [
      signature,
      signatureBytes,
      publicKey,
      error,
      code,
      algorithm,
      keySize,
    ]
  }
  static func == (lhs: SignatureResult, rhs: SignatureResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DecryptResult: Hashable {
  var decryptedData: String? = nil
  var error: String? = nil
  var code: BiometricError? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DecryptResult? {
    let decryptedData: String? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])
    let code: BiometricError? = nilOrValue(pigeonVar_list[2])

    return DecryptResult(
      decryptedData: decryptedData,
      error: error,
      code: code
    )
  }
  func toList() -> [Any?] {
    return [
      decryptedData,
      error,
      code,
    ]
  }
  static func == (lhs: DecryptResult, rhs: DecryptResult) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Detailed information about existing biometric keys.
///
/// Generated class from Pigeon that represents data sent in messages.
struct KeyInfo: Hashable {
  /// Whether any biometric key exists on the device.
  var exists: Bool? = nil
  /// Whether the key is still valid (not invalidated by biometric changes).
  /// Only populated when `checkValidity: true` is passed.
  var isValid: Bool? = nil
  /// The algorithm of the signing key (e.g., "RSA", "EC").
  var algorithm: String? = nil
  /// The key size in bits (e.g., 2048 for RSA, 256 for EC).
  var keySize: Int64? = nil
  /// Whether the key is in hybrid mode (separate signing and decryption keys).
  var isHybridMode: Bool? = nil
  /// Signing key public key (formatted according to the requested format).
  var publicKey: String? = nil
  /// Decryption key public key for hybrid mode.
  var decryptingPublicKey: String? = nil
  /// Algorithm of the decryption key (hybrid mode only).
  var decryptingAlgorithm: String? = nil
  /// Key size of the decryption key in bits (hybrid mode only).
  var decryptingKeySize: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KeyInfo? {
    let exists: Bool? = nilOrValue(pigeonVar_list[0])
    let isValid: Bool? = nilOrValue(pigeonVar_list[1])
    let algorithm: String? = nilOrValue(pigeonVar_list[2])
    let keySize: Int64? = nilOrValue(pigeonVar_list[3])
    let isHybridMode: Bool? = nilOrValue(pigeonVar_list[4])
    let publicKey: String? = nilOrValue(pigeonVar_list[5])
    let decryptingPublicKey: String? = nilOrValue(pigeonVar_list[6])
    let decryptingAlgorithm: String? = nilOrValue(pigeonVar_list[7])
    let decryptingKeySize: Int64? = nilOrValue(pigeonVar_list[8])

    return KeyInfo(
      exists: exists,
      isValid: isValid,
      algorithm: algorithm,
      keySize: keySize,
      isHybridMode: isHybridMode,
      publicKey: publicKey,
      decryptingPublicKey: decryptingPublicKey,
      decryptingAlgorithm: decryptingAlgorithm,
      decryptingKeySize: decryptingKeySize
    )
  }
  func toList() -> [Any?] {
    return [
      exists,
      isValid,
      algorithm,
      keySize,
      isHybridMode,
      publicKey,
      decryptingPublicKey,
      decryptingAlgorithm,
      decryptingKeySize,
    ]
  }
  static func == (lhs: KeyInfo, rhs: KeyInfo) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for Android key creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidCreateKeysConfig: Hashable {
  var enableDecryption: Bool? = nil
  var promptSubtitle: String? = nil
  var promptDescription: String? = nil
  var cancelButtonText: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidCreateKeysConfig? {
    let enableDecryption: Bool? = nilOrValue(pigeonVar_list[0])
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[1])
    let promptDescription: String? = nilOrValue(pigeonVar_list[2])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[3])

    return AndroidCreateKeysConfig(
      enableDecryption: enableDecryption,
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText
    )
  }
  func toList() -> [Any?] {
    return [
      enableDecryption,
      promptSubtitle,
      promptDescription,
      cancelButtonText,
    ]
  }
  static func == (lhs: AndroidCreateKeysConfig, rhs: AndroidCreateKeysConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for iOS key creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IosCreateKeysConfig: Hashable {
  var reserved: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosCreateKeysConfig? {
    let reserved: String? = nilOrValue(pigeonVar_list[0])

    return IosCreateKeysConfig(
      reserved: reserved
    )
  }
  func toList() -> [Any?] {
    return [
      reserved
    ]
  }
  static func == (lhs: IosCreateKeysConfig, rhs: IosCreateKeysConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for macOS key creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MacosCreateKeysConfig: Hashable {
  var reserved: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MacosCreateKeysConfig? {
    let reserved: String? = nilOrValue(pigeonVar_list[0])

    return MacosCreateKeysConfig(
      reserved: reserved
    )
  }
  func toList() -> [Any?] {
    return [
      reserved
    ]
  }
  static func == (lhs: MacosCreateKeysConfig, rhs: MacosCreateKeysConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for Android signature creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidCreateSignatureConfig: Hashable {
  var promptSubtitle: String? = nil
  var promptDescription: String? = nil
  var cancelButtonText: String? = nil
  var allowDeviceCredentials: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidCreateSignatureConfig? {
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[0])
    let promptDescription: String? = nilOrValue(pigeonVar_list[1])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[2])
    let allowDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[3])

    return AndroidCreateSignatureConfig(
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText,
      allowDeviceCredentials: allowDeviceCredentials
    )
  }
  func toList() -> [Any?] {
    return [
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
    ]
  }
  static func == (lhs: AndroidCreateSignatureConfig, rhs: AndroidCreateSignatureConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for iOS signature creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IosCreateSignatureConfig: Hashable {
  var shouldMigrate: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosCreateSignatureConfig? {
    let shouldMigrate: Bool? = nilOrValue(pigeonVar_list[0])

    return IosCreateSignatureConfig(
      shouldMigrate: shouldMigrate
    )
  }
  func toList() -> [Any?] {
    return [
      shouldMigrate
    ]
  }
  static func == (lhs: IosCreateSignatureConfig, rhs: IosCreateSignatureConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for macOS signature creation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MacosCreateSignatureConfig: Hashable {
  var reserved: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MacosCreateSignatureConfig? {
    let reserved: String? = nilOrValue(pigeonVar_list[0])

    return MacosCreateSignatureConfig(
      reserved: reserved
    )
  }
  func toList() -> [Any?] {
    return [
      reserved
    ]
  }
  static func == (lhs: MacosCreateSignatureConfig, rhs: MacosCreateSignatureConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for Android decryption.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AndroidDecryptConfig: Hashable {
  var promptSubtitle: String? = nil
  var promptDescription: String? = nil
  var cancelButtonText: String? = nil
  var allowDeviceCredentials: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidDecryptConfig? {
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[0])
    let promptDescription: String? = nilOrValue(pigeonVar_list[1])
    let cancelButtonText: String? = nilOrValue(pigeonVar_list[2])
    let allowDeviceCredentials: Bool? = nilOrValue(pigeonVar_list[3])

    return AndroidDecryptConfig(
      promptSubtitle: promptSubtitle,
      promptDescription: promptDescription,
      cancelButtonText: cancelButtonText,
      allowDeviceCredentials: allowDeviceCredentials
    )
  }
  func toList() -> [Any?] {
    return [
      promptSubtitle,
      promptDescription,
      cancelButtonText,
      allowDeviceCredentials,
    ]
  }
  static func == (lhs: AndroidDecryptConfig, rhs: AndroidDecryptConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for iOS decryption.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IosDecryptConfig: Hashable {
  var shouldMigrate: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosDecryptConfig? {
    let shouldMigrate: Bool? = nilOrValue(pigeonVar_list[0])

    return IosDecryptConfig(
      shouldMigrate: shouldMigrate
    )
  }
  func toList() -> [Any?] {
    return [
      shouldMigrate
    ]
  }
  static func == (lhs: IosDecryptConfig, rhs: IosDecryptConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

/// Configuration for macOS decryption.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MacosDecryptConfig: Hashable {
  var reserved: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MacosDecryptConfig? {
    let reserved: String? = nilOrValue(pigeonVar_list[0])

    return MacosDecryptConfig(
      reserved: reserved
    )
  }
  func toList() -> [Any?] {
    return [
      reserved
    ]
  }
  static func == (lhs: MacosDecryptConfig, rhs: MacosDecryptConfig) -> Bool {
    return deepEqualsBiometricSignatureApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBiometricSignatureApi(value: toList(), hasher: &hasher)
  }
}

private class BiometricSignatureApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BiometricError(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SignatureType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KeyFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SignatureFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PayloadFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return BiometricAvailability.fromList(self.readValue() as! [Any?])
    case 136:
      return KeyCreationResult.fromList(self.readValue() as! [Any?])
    case 137:
      return SignatureResult.fromList(self.readValue() as! [Any?])
    case 138:
      return DecryptResult.fromList(self.readValue() as! [Any?])
    case 139:
      return KeyInfo.fromList(self.readValue() as! [Any?])
    case 140:
      return AndroidCreateKeysConfig.fromList(self.readValue() as! [Any?])
    case 141:
      return IosCreateKeysConfig.fromList(self.readValue() as! [Any?])
    case 142:
      return MacosCreateKeysConfig.fromList(self.readValue() as! [Any?])
    case 143:
      return AndroidCreateSignatureConfig.fromList(self.readValue() as! [Any?])
    case 144:
      return IosCreateSignatureConfig.fromList(self.readValue() as! [Any?])
    case 145:
      return MacosCreateSignatureConfig.fromList(self.readValue() as! [Any?])
    case 146:
      return AndroidDecryptConfig.fromList(self.readValue() as! [Any?])
    case 147:
      return IosDecryptConfig.fromList(self.readValue() as! [Any?])
    case 148:
      return MacosDecryptConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BiometricSignatureApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BiometricType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricError {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? SignatureType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? KeyFormat {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? SignatureFormat {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PayloadFormat {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? BiometricAvailability {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? KeyCreationResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? SignatureResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? DecryptResult {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? KeyInfo {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidCreateKeysConfig {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? IosCreateKeysConfig {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? MacosCreateKeysConfig {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidCreateSignatureConfig {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? IosCreateSignatureConfig {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? MacosCreateSignatureConfig {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidDecryptConfig {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? IosDecryptConfig {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? MacosDecryptConfig {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BiometricSignatureApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BiometricSignatureApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BiometricSignatureApiPigeonCodecWriter(data: data)
  }
}

class BiometricSignatureApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BiometricSignatureApiPigeonCodec(readerWriter: BiometricSignatureApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BiometricSignatureApi {
  /// Checks if biometric authentication is available.
  func biometricAuthAvailable() throws -> BiometricAvailability
  /// Creates a new key pair.
  func createKeys(androidConfig: AndroidCreateKeysConfig?, iosConfig: IosCreateKeysConfig?, macosConfig: MacosCreateKeysConfig?, useDeviceCredentials: Bool?, signatureType: SignatureType?, setInvalidatedByBiometricEnrollment: Bool?, keyFormat: KeyFormat, enforceBiometric: Bool, promptMessage: String?, completion: @escaping (Result<KeyCreationResult, Error>) -> Void)
  /// Creates a signature.
  func createSignature(payload: String, androidConfig: AndroidCreateSignatureConfig?, iosConfig: IosCreateSignatureConfig?, macosConfig: MacosCreateSignatureConfig?, signatureFormat: SignatureFormat, keyFormat: KeyFormat, promptMessage: String?, completion: @escaping (Result<SignatureResult, Error>) -> Void)
  /// Decrypts data.
  func decrypt(payload: String, payloadFormat: PayloadFormat, androidConfig: AndroidDecryptConfig?, iosConfig: IosDecryptConfig?, macosConfig: MacosDecryptConfig?, promptMessage: String?, completion: @escaping (Result<DecryptResult, Error>) -> Void)
  /// Deletes keys.
  func deleteKeys() throws -> Bool
  /// Gets detailed information about existing biometric keys.
  ///
  /// Returns key metadata including algorithm, size, validity, and public keys.
  func getKeyInfo(checkValidity: Bool, keyFormat: KeyFormat, completion: @escaping (Result<KeyInfo, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BiometricSignatureApiSetup {
  static var codec: FlutterStandardMessageCodec { BiometricSignatureApiPigeonCodec.shared }
  /// Sets up an instance of `BiometricSignatureApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BiometricSignatureApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Checks if biometric authentication is available.
    let biometricAuthAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.biometricAuthAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      biometricAuthAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.biometricAuthAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      biometricAuthAvailableChannel.setMessageHandler(nil)
    }
    /// Creates a new key pair.
    let createKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let androidConfigArg: AndroidCreateKeysConfig? = nilOrValue(args[0])
        let iosConfigArg: IosCreateKeysConfig? = nilOrValue(args[1])
        let macosConfigArg: MacosCreateKeysConfig? = nilOrValue(args[2])
        let useDeviceCredentialsArg: Bool? = nilOrValue(args[3])
        let signatureTypeArg: SignatureType? = nilOrValue(args[4])
        let setInvalidatedByBiometricEnrollmentArg: Bool? = nilOrValue(args[5])
        let keyFormatArg = args[6] as! KeyFormat
        let enforceBiometricArg = args[7] as! Bool
        let promptMessageArg: String? = nilOrValue(args[8])
        api.createKeys(androidConfig: androidConfigArg, iosConfig: iosConfigArg, macosConfig: macosConfigArg, useDeviceCredentials: useDeviceCredentialsArg, signatureType: signatureTypeArg, setInvalidatedByBiometricEnrollment: setInvalidatedByBiometricEnrollmentArg, keyFormat: keyFormatArg, enforceBiometric: enforceBiometricArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createKeysChannel.setMessageHandler(nil)
    }
    /// Creates a signature.
    let createSignatureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.createSignature\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSignatureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! String
        let androidConfigArg: AndroidCreateSignatureConfig? = nilOrValue(args[1])
        let iosConfigArg: IosCreateSignatureConfig? = nilOrValue(args[2])
        let macosConfigArg: MacosCreateSignatureConfig? = nilOrValue(args[3])
        let signatureFormatArg = args[4] as! SignatureFormat
        let keyFormatArg = args[5] as! KeyFormat
        let promptMessageArg: String? = nilOrValue(args[6])
        api.createSignature(payload: payloadArg, androidConfig: androidConfigArg, iosConfig: iosConfigArg, macosConfig: macosConfigArg, signatureFormat: signatureFormatArg, keyFormat: keyFormatArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSignatureChannel.setMessageHandler(nil)
    }
    /// Decrypts data.
    let decryptChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.decrypt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decryptChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let payloadArg = args[0] as! String
        let payloadFormatArg = args[1] as! PayloadFormat
        let androidConfigArg: AndroidDecryptConfig? = nilOrValue(args[2])
        let iosConfigArg: IosDecryptConfig? = nilOrValue(args[3])
        let macosConfigArg: MacosDecryptConfig? = nilOrValue(args[4])
        let promptMessageArg: String? = nilOrValue(args[5])
        api.decrypt(payload: payloadArg, payloadFormat: payloadFormatArg, androidConfig: androidConfigArg, iosConfig: iosConfigArg, macosConfig: macosConfigArg, promptMessage: promptMessageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      decryptChannel.setMessageHandler(nil)
    }
    /// Deletes keys.
    let deleteKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.deleteKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteKeysChannel.setMessageHandler { _, reply in
        do {
          let result = try api.deleteKeys()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteKeysChannel.setMessageHandler(nil)
    }
    /// Gets detailed information about existing biometric keys.
    ///
    /// Returns key metadata including algorithm, size, validity, and public keys.
    let getKeyInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.biometric_signature.BiometricSignatureApi.getKeyInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeyInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let checkValidityArg = args[0] as! Bool
        let keyFormatArg = args[1] as! KeyFormat
        api.getKeyInfo(checkValidity: checkValidityArg, keyFormat: keyFormatArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getKeyInfoChannel.setMessageHandler(nil)
    }
  }
}
